export const settingPayload = {
    update: {
        shop_name: "", 
        logo: "", 
        phone: "", 
        email: "",
        address: "",
        tax: "",
    },
    store: {
        shop_name: "", 
        logo: "", 
        phone: "",
        email: "",
        address: "",
        tax: "",
    },
    columnsName: 'settingColumns',
    columns: [
        { id: "id", label: "Id", minWidth: 60 },
        { id: "shop_name", label: "Shop name", minWidth: 100 },
        { id: "logo", label: "logo", minWidth: 150 },
        { id: "phone", label: "Phone", minWidth: 200 },
        { id: "email", label: "Email", minWidth: 100 },
        { id: "address", label: "Address", minWidth: 100 },
        { id: "tax", label: "Tax", minWidth: 100 },
    ],
    paginateParams: {
        page: 1,
        per_page: 5,
        columns: "shop_name, logo, phone, email, address, tax",
        search: "",
        order: "id",
        sort: "DESC",
        value: "",
        start_date: "",
        end_date: "",
    },
};
